### ISSUE TITLE
Guide to ubuntu(and derivatives) users experiencing 'illegal hardware instruction'

### ISSUE THREAD

**Issue by zero734kr** [kijk2869/discodo#110]
I solved this problem by running the following commands, and my system is ``Linux Mint 20 Ulyana``.

```sh
sudo apt update
sudo apt install --no-install-recommends -y gcc libopus-dev python3-dev libnacl-dev
sudo apt install --no-install-recommends -y pkg-config ffmpeg libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev
python3.8 -m pip install av --no-binary av --force
```
Please share your method of solving if you are using other distributions in the comments to contribute

**Comment by kijk2869** [comment]
It might be `PyAV` bug.

Thanks for your contribution

**Comment by zero734kr** [comment]
Also it had no problems with Linux Mint 21 Ulyssa
