### ISSUE TITLE
[Enhancement] Please make slogan.

### ISSUE THREAD

**Issue by wonderlandpark** [kijk2869/discodo#12]
Pls

**Comment by kijk2869** [comment]
Tell me why it needs.

**Comment by wonderlandpark** [comment]
Firstly. Slogan is 간지 it looks very nice
Secondly. 홍보효과 어그로 is 쌉가능
Lastly. Slogan is important for project starts with `dis` so I told you to change repo name to `Thiscord`

**Comment by sannoob** [comment]
I suggest "Simple, Fastest Music Extension for your project"

**Comment by kijk2869** [comment]
그런 장점이 있다면, PR을 넣어주세요, 기여해주셔서 감사합니다.

If it has such an advantage, please add a PR, thank you for your contribution.

**Comment by wonderlandpark** [comment]
Or `Sexy Music for your Discord. Thiscord.`
