### ISSUE TITLE
voice connection of <ID> destroyed with 1006. wait for events.

### ISSUE THREAD

**Issue by simsimler** [kijk2869/discodo#124]
While playing music, the following logs appear and the music does not play.
`[2021-01-12 22:05:04,235] [connector.py] [discodo.VoiceConnector:connector] [INFO]: voice connection of 748691436647612488 destroyed with 1006. wait for events.`

**Comment by kijk2869** [comment]
We need how it happened.

**Comment by SaidBySolo** [comment]
To be able to reproduce
Can you write the environment you are using and detailed information?

**Comment by kijk2869** [comment]
https://websockets.readthedocs.io/en/stable/faq.html#what-does-connectionclosederror-code-1006-mean

If it can be reproduce, tell us with `websockets` DEBUG logs.

**Comment by simsimler** [comment]
I tried to reproduce the situation, and as a reproduce, I got the following results.
It happened while playing music for more than an hour.
And the discodo server output the following logs:`[2021-01-15 22:05:49,029] [connector.py] [discodo.VoiceConnector:connector] [INFO]: voice connection of 773105523242827796 destroyed with 1006. wait for events.
websocket connection is closing.
`
I'm using Raspberry Pi 4B and OS is Raspberry Pi OS
The Python version is 3.8.6 and discodo module version is 2.3.9

**Comment by kijk2869** [comment]
> I tried to reproduce the situation, and as a reproduce, I got the following results.
> It happened while playing music for more than an hour.
> And the discodo server output the following logs:`[2021-01-15 22:05:49,029] [connector.py] [discodo.VoiceConnector:connector] [INFO]: voice connection of 773105523242827796 destroyed with 1006. wait for events.
> 
> websocket connection is closing.
> `
> I'm using Raspberry Pi 4B and OS is Raspberry Pi OS
> The Python version is 3.8.6 and discodo module version is 2.3.9

Please give us `aiohttp` DEBUG logs.
