### ISSUE TITLE
Name of files cases are different.

### ISSUE THREAD

**Issue by wonderlandpark** [kijk2869/discodo#2]
Some files are using CamelCase but, some files are using snake_case. This makes me confusing.

**Comment by kijk2869** [comment]
I used CamelCase on property, and used snake_case on method.

**Comment by wonderlandpark** [comment]
I meant CamelCases for fileName

**Comment by wonderlandpark** [comment]
Maybe PascalCase confused with camelCase

**Comment by sannoob** [comment]
어쩌라고요

**Comment by wonderlandpark** [comment]
I really need this. Plz solve it fast!!

**Comment by sannoob** [comment]
> I really need this. Plz solve it fast!!

만약 당신이 camalCase와 PascalCase 의 혼용이 불편하다면, 당신은 이 레포지토리를 포크 후, 풀 리퀘스트를 넣을 수 있습니다
Try it! :D

**Comment by wonderlandpark** [comment]
I am newbie for github (making sad face)

And I cant do Korean. Can you plz talk with eng?
