### ISSUE TITLE
change framework from sanic to fastapi

### ISSUE THREAD

**Issue by kijk2869** [kijk2869/discodo#44]

**Comment by kijk2869** [comment]
https://docs.vibora.io/

**Comment by sannoob** [comment]
https://github.com/vibora-io/vibora/tree/master

![image](https://user-images.githubusercontent.com/40298015/93104695-282be680-f6e9-11ea-8678-1d7dc1338291.png)

![image](https://user-images.githubusercontent.com/40298015/93104733-31b54e80-f6e9-11ea-8f5d-7999da0f35ae.png)

It seems unstable framework

**Comment by sannoob** [comment]
https://github.com/vibora-io/vibora/issues/253

**Comment by sannoob** [comment]
vibora -> fastapi

https://fastapi.tiangolo.com/advanced/websockets/

https://fastapi.tiangolo.com/advanced/custom-response/#streamingresponse

**Comment by sannoob** [comment]
https://github.com/tiangolo/fastapi

**Comment by kijk2869** [comment]
fastapi need uvicorn or gunicorn to run
