### ISSUE TITLE
[TODO] Spotify support

### ISSUE THREAD

**Issue by kijk2869** [kijk2869/discodo#47]

**Comment by kijk2869** [comment]
https://developer.spotify.com/documentation/web-api/

**Comment by kijk2869** [comment]
**⚠️ WAITING, I NEED MORE INFORMATION**

need spotify url examples.

**Comment by wonderlandpark** [comment]
Playlist: https://open.spotify.com/playlist/37i9dQZF1DX0y9CwEpdGpz?si=ca3qVus2TgqOYyGJtWo2Rw (URI: `spotify:playlist:37i9dQZF1DX0y9CwEpdGpz`)
Song: https://open.spotify.com/track/0pYacDCZuRhcrwGUA5nTBe?si=B9v1bC14S_OtdPz58ac8Aw (URI: `spotify:track:0pYacDCZuRhcrwGUA5nTBe`)
