### ISSUE TITLE
[Questions] stat not found

### ISSUE THREAD

**Issue by AkiaCode** [kijk2869/discodo#70]
![image](https://user-images.githubusercontent.com/71239005/96672972-64193200-13a0-11eb-92cf-722caf4adb0a.png)
![image](https://user-images.githubusercontent.com/71239005/96673126-c4a86f00-13a0-11eb-95c8-72ed71824c0f.png)

Is this originally right?

**Comment by AkiaCode** [comment]
![image](https://user-images.githubusercontent.com/71239005/96674312-7ea0da80-13a3-11eb-9e29-0cbb49f55fb7.png)

**Comment by kijk2869** [comment]
It's look like that there is typo error in `STAT`, `STATUS`, `STATE`.

Originally, `STATUS` means server status, and `STATE` means voice client state (ex queue, playing source, options).

I will fix it, thanks for reporting.

**Comment by AkiaCode** [comment]
Okay, thank for @kijk2869
