### ISSUE TITLE
[Feature Request] Support Local File Path

### ISSUE THREAD

**Issue by AkiaCode** [kijk2869/discodo#71]

**Comment by kijk2869** [comment]
Must not be passed to `youtube_dl` to process FilePath-like.

**Comment by kijk2869** [comment]
What `music url` means?

@AkiaCode

**Comment by AkiaCode** [comment]
ex ) https://localhost:3000/muisc.mp3

@kijk2869

**Comment by kijk2869** [comment]
> ex ) https://localhost:3000/muisc.mp3
> 
> @kijk2869 

Already supported 😃

**Comment by AkiaCode** [comment]
oh, okay

**Comment by kijk2869** [comment]
`Local File Path` is not supported.

**Comment by AkiaCode** [comment]
sorry
