### ISSUE TITLE
[Feature Request] Docs Korean version

### ISSUE THREAD

**Issue by AkiaCode** [kijk2869/discodo#74]
How about explaining in Korean at the level that even **Jammin** can see?

**Comment by ReDesignedJP** [comment]
Get older

**Comment by AkiaCode** [comment]
ok, then JamminUp?

right? @ReDesignedJP

**Comment by SaidBySolo** [comment]
References should be written under the assumption that you know Python. Also, there is currently no English docs written.

**Comment by SaidBySolo** [comment]
I also know that there are client changes in Discodo's roadmap. I don't think I'm ready to write Docs yet.

**Comment by AkiaCode** [comment]
@SaidBySolo  Okay

**Comment by ReDesignedJP** [comment]
![Uploading Screenshot_20201027-075301_Gmail.jpg …]()
Unbelievable lol
